name: jobhubv2_0
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  http: ^1.3.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^4.0.3
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.4+1
  flutter_chat_bubble: ^2.0.2
  flutter_animate: ^4.1.1+1
  image_cropper: ^9.0.0
  image_picker: ^0.8.7+4
  file_picker: ^5.3.0
  cached_network_image: ^3.2.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  uuid: ^3.0.7
  intl: ^0.18.1
  cloud_firestore: ^5.6.6
  lottie: ^2.6.0
  win32: ^5.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

 